version: "3.0"
services:
  db:
    image: redis:latest
    volumes:
      - ./redis/dump.rdb:/data/dump.rdb
  web:
    build: .
    container_name: cognosaurus
    command: bash -c "
      python manage.py migrate
      && uvicorn --host ${HOST} --port ${PORT} cognosaurus.asgi:application"
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
